import Head from "next/head";
import { useState, useEffect } from "react";
import { Layout } from "@/components/layout/Layout";

type Post = {
  id: string;
  name: string;
  message: string;
  secret?: string;
  createdAt: string;
  img: string;
};

const PostComponent = ({ post }: { post: Post }) => (
  <div className=" w-full bg-white border-b-2 pt-10 pb-20">
    <div className="flex items-center space-x-4">
      <img
        src={post.img || "https://via.placeholder.com/50"}
        alt="Avatar"
        className="block mx-auto object-cover rounded-full h-10 w-10 "
      />
      <div className="flex-grow">
        <div className="text-sm text-gray-600 font-semibold  flex items-center justify-between">
          <div>{post.name}</div>
          <span className="font-normal text-gray-500">
            {new Date(post.createdAt).toLocaleString()}
          </span>
        </div>
        <div className="mt-2 text-xl font-light text-gray-600">
          {post.message}
        </div>
      </div>
    </div>
  </div>
);

export default function Home() {
  const [posts, setPosts] = useState<Post[]>([]);

  useEffect(() => {
    const fetchPosts = async () => {
      try {
        const response = await fetch("/api/posts");
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        let { data } = await response.json();

        data = data.sort((a, b) => {
          const dateA = new Date(a.createdAt);
          const dateB = new Date(b.createdAt);
          return dateB - dateA;
        });

        setPosts(data);
      } catch (error) {
        console.error("Fetching posts failed", error);
      }
    };

    fetchPosts();
  }, []);

  return (
    <Layout>
      <Head>
        <title>Ataani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-start">
        <h1 className="text-4xl font-bold">Inicio/Tuxt a meyaj</h1>
        <div className="w-full">
          {posts.map((post) => (
            <PostComponent key={post.id} post={post} />
          ))}
        </div>
      </div>
    </Layout>
  );
}
