import Head from "next/head";
import { useState, useEffect } from "react";
import { Layout } from "@/components/layout/Layout";

interface Post {
  id: number;
  name: string;
  message: string;
  categories: string[];
  createdAt: string;
}

export default function Home() {
  const [posts, setPosts] = useState<Post[] | null>(null);

  useEffect(() => {
    const fetchPosts = async () => {
      try {
        const response = await fetch("/api/posts");
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
        const { data } = await response.json();
        setPosts(data);
      } catch (error) {
        console.error("Fetching posts failed", error);
      }
    };

    fetchPosts();
  }, []);

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-4xl font-bold">All messages</h1>

        <div className="cursor-pointer mt-5 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {posts &&
            posts.map((post) => (
              <div
                key={post.id}
                className="border-gray-200 border-2 rounded-md p-3 bg-white shadow-md hover:shadow-lg transition-shadow duration-300 ease-in-out"
              >
                {post.categories && (
                  <div className="flex space-x-1 flex-wrap">
                    {post.categories.map((category) => (
                      <span
                        key={category}
                        className="inline-block bg-gray-200 rounded-full px-3 mb-2 text-sm font-semibold text-gray-700 mr-2"
                      >
                        {category}
                      </span>
                    ))}
                  </div>
                )}
                <p className="text-lg font-semibold">{post.message}</p>
                <p className="text-gray-500 text-sm mt-2">
                  {post.name} | {new Date(post.createdAt).toLocaleString()}
                </p>
              </div>
            ))}
        </div>
      </div>
    </Layout>
  );
}
